const BRANDS = {
  amazon: {
    name: 'Amazon',
    title: 'Sell Your Amazon Gift Card for Cash',
    description: 'Turn unused Amazon gift cards into real cash on Swapio. Get 95% of your balance via PayPal, Cash App, Zelle, Venmo, Bitcoin, or bank transfer.',
    gradient: 'from-swapio-dark to-swapio-light',
    intro: 'Amazon is the most swapped brand on Swapio. Enter your balance, see your offer instantly, and get paid within hours.',
    highlights: [
      '95% payout — flat 5% fee shown upfront',
      'Balances from $10 to $5,000 accepted',
      'PayPal, Cash App, Zelle, Venmo, Bitcoin, or bank transfer',
      'Just your Amazon claim code to submit',
    ],
  },
  apple: {
    name: 'Apple',
    title: 'Sell Your Apple Gift Card for Cash',
    description: 'Swap unused Apple gift cards for cash on Swapio. Receive 95% of your card value paid quickly via your preferred payout method.',
    gradient: 'from-swapio-light to-swapio-dark/60',
    intro: 'Apple gift cards hold strong value year-round. Swapio makes it easy to convert yours to spendable cash.',
    highlights: [
      'Digital and physical Apple cards accepted',
      'See your exact cash offer before you submit',
      'Verified and paid within hours',
      'Secure HTTPS submission',
    ],
  },
  visa: {
    name: 'Visa',
    title: 'Sell Your Visa Gift Card for Cash',
    description: 'Convert Visa prepaid gift cards to cash on Swapio. Get 95% of your balance with transparent fees and fast payouts.',
    gradient: 'from-swapio-dark/80 to-swapio-light/80',
    intro: 'Visa prepaid cards swap fast on Swapio — they verify quickly and payouts land in hours.',
    highlights: [
      'Open-loop prepaid cards welcome',
      'Card number, expiration, and CVV required',
      'Six payout methods available',
      'Order code (SWP-XXXXXX) for every swap',
    ],
  },
  target: {
    name: 'Target',
    title: 'Sell Your Target Gift Card for Cash',
    description: 'Sell Target gift cards for cash on Swapio. Receive 95% of your balance via PayPal, Cash App, Zelle, and more.',
    gradient: 'from-swapio-bg to-swapio-light/40',
    intro: 'Got a Target card you won\'t use? Swap it for real money you can spend anywhere.',
    highlights: [
      'One of the most popular retail cards on Swapio',
      'Card number and PIN required',
      'No hidden fees — 5% service fee shown upfront',
      'Paid within hours of verification',
    ],
  },
  steam: {
    name: 'Steam',
    title: 'Sell Your Steam Gift Card for Cash',
    description: 'Turn Steam wallet codes into cash on Swapio. Get 95% of your card value paid via PayPal, Cash App, Zelle, Venmo, Bitcoin, or bank transfer.',
    gradient: 'from-swapio-dark to-swapio-light/50',
    intro: 'Steam cards swap quickly on Swapio — especially popular during sale season.',
    highlights: [
      'Digital redemption code required',
      'Instant offer preview on the homepage',
      'Gaming cards verified fast',
      'Cash you can use anywhere',
    ],
  },
  'google-play': {
    name: 'Google Play',
    title: 'Sell Your Google Play Gift Card for Cash',
    description: 'Swap Google Play gift cards for cash on Swapio. Receive 95% of your balance with fast, secure payouts.',
    gradient: 'from-swapio-light/70 to-white',
    intro: 'Don\'t have apps to buy? Convert your Google Play balance to real cash instead.',
    highlights: [
      'Google Play gift code required',
      'Balances $10–$5,000 accepted',
      'Transparent 95% payout rate',
      'Multiple payout options',
    ],
  },
  playstation: {
    name: 'PlayStation',
    title: 'Sell Your PlayStation Gift Card for Cash',
    description: 'Sell PlayStation gift cards for cash on Swapio. Get 95% of your balance paid quickly via your chosen payout method.',
    gradient: 'from-swapio-dark to-swapio-light/70',
    intro: 'PlayStation wallet funds sitting unused? Swapio turns them into cash in your pocket.',
    highlights: [
      'Digital code submission',
      'Popular with gaming card swaps',
      'Offer shown before you commit',
      'Paid within hours',
    ],
  },
  walmart: {
    name: 'Walmart',
    title: 'Sell Your Walmart Gift Card for Cash',
    description: 'Convert Walmart gift cards to cash on Swapio. Get 95% of your card value via PayPal, Cash App, Zelle, Venmo, Bitcoin, or bank transfer.',
    gradient: 'from-swapio-light to-swapio-dark/50',
    intro: 'Walmart cards are among the most commonly received in the US — swap yours for flexible cash.',
    highlights: [
      'Card number and PIN required',
      'Big-box retail cards in high demand',
      'Flat 5% fee, no surprises',
      'Six payout methods to choose from',
    ],
  },
};